I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 294, in script
    scene bg sunrise with fadein
  File "game/script.rpy", line 294, in <module>
    scene bg sunrise with fadein
NameError: name 'fadein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 294, in script
    scene bg sunrise with fadein
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 1385, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 294, in <module>
    scene bg sunrise with fadein
NameError: name 'fadein' is not defined

Darwin-19.3.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
Demo 1.0
Mon Oct 12 22:12:01 2020
